### ISSUE TITLE
`open_loop': redirection forbidden: http://www.olgr.nsw.gov.au/liquor_applications/xml/application%20noticeboard%20data.xml 

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/nsw_office_of_liquor_gaming_and_racing#1]
```
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://www.olgr.nsw.gov.au/liquor_applications/xml/application%20noticeboard%20data.xml -> https://www.liquorandgaming.justice.nsw.gov.au/ (RuntimeError)
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/open-uri.rb:678:in `open'
 	from /app/vendor/ruby-1.9.3/lib/ruby/1.9.1/open-uri.rb:33:in `open'
 	from scraper.rb:5:in `<main>'
```

https://www.liquorandgaming.justice.nsw.gov.au/pages/public-consultation/online-application-noticeboard/online-application-noticeboard.aspx seems to be the place to search now; and we'd have to search by date range.

**Comment by henare** [comment]
Sucks that XML isn't there any more but there's JSON under the hood of that page so it could be even nicer to scrape :+1:

**Comment by henare** [comment]
@aidanarcher and I have found that the applications are available as XML at a URL like:

https://www.liquorandgaming.justice.nsw.gov.au/_api/search/query?querytext=%27%28%20NoticeboardDatePosted:2016-04-19..2016-04-20%29%20ContentSource:Notices%27&rowlimit=4000&selectproperties=%27NoticeboardApplicationNumber,NoticeboardApplicationType,NoticeboardCIS,NoticeboardDatePosted,NoticeboardDatePostedString,NoticeboardLGA,NoticeboardLIA,NoticeboardLPN,NoticeboardNotice,NoticeboardPostcode,NoticeboardPLN,NoticeboardSubmissionDate,NoticeboardSubmissionDateString,NoticeboardStreetAddress,NoticeboardSuburb,NoticeboardStatus,NoticeboardRST%27&sortlist=%27NoticeboardDatePosted:descending%27&QueryTemplatePropertiesUrl=%27spfile://webroot/queryparametertemplate.xml%27

The XML is truly awful and it's very difficult to search through :cry:
